### ISSUE TITLE
Cache clear, session

### ISSUE THREAD

**Issue by pierrre** [FriendsOfSymfony/FOSFacebookBundle#166]
I'm using Symfony 2.1 beta2 + FOSFacebookBundle.
When I clear the cache, I get this error:

```
Notice: A session had already been started - ignoring session_start() in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 146
```

**Comment by pierrre** [comment]
I get a similar error when I install vendors:

```
Fatal error: Uncaught exception 'ErrorException' with message 'Warning: file_put_contents(/home/pierre/Git/Plyce/Plyce-Server/app/cache/dev/sessions/sess_32p4iu39kkvbcov16tr5td5m61): failed to open stream: No such file or directory in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php line 82' in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php:82
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'file_put_conten...', '/home/pierre/Gi...', 82, Array)
#1 /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php(82): file_put_contents('/home/pierre/Gi...', '_sf2_attributes...')
#2 /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerPr in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php on line 82
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Warning: file_put_contents(/home/pierre/Git/Plyce/Plyce-Server/app/cache/dev/sessions/sess_32p4iu39kkvbcov16tr5td5m61): failed to open stream: No such file or directory in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php line 82' in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php:82
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'file_put_conten...', '/home/pierre/Gi...', 82, Array)
#1 /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php(82): file_put_contents('/home/pierre/Gi...', '_sf2_attributes...')
#2 /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerPr in /home/pierre/Git/Plyce/Plyce-Server/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/FileSessionHandler.php on line 82
```

**Comment by diegoholiveira** [comment]
What's the FOSFacebookBundle used? This error still happen with 1.1 stable?
